services:
  - type: web
    name: parcel-damage-backend
    env: python
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.8"
    buildFilter:
      paths:
        - "requirements.txt"
        - "backend/**"
        - "models/resnet34_model.tflite"
        - "run.py"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    plan: free
